### ISSUE TITLE
Debian packages use weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by iheinrich** [owncloud/owncloud.org#916] opened 2016-04-03 14:20 UTC
Since updating Debian APT to 1.2.7 I get a warning related to owncloud.org repositories:
`sudo apt-get update`
`[...]`
`W: http://download.owncloud.org/download/repositories/9.0/Debian_8.0/Release.gpg: Signature by key BCECA90325B072AB1245F739AB7C32C35180350A uses weak digest algorithm (SHA1)`

This warning is related to the planned removal of SHA1 algorithm for package signing from APT. As per Debian wiki this is fixable by using SHA256 or SHA512 for package signing:
"The repository owner needs to pass --digest-algo SHA512 or --digest-algo SHA256 (or another SHA2 algorithm) to gpg when signing the file." [https://wiki.debian.org/Teams/Apt/Sha1Removal](https://wiki.debian.org/Teams/Apt/Sha1Removal)
A few more details can be found at [https://juliank.wordpress.com/2016/03/15/clarifications-and-updates-on-apt-sha1/](https://juliank.wordpress.com/2016/03/15/clarifications-and-updates-on-apt-sha1/)

**Comment by danimo** [comment] 2016-04-03 15:58
Duplicate of https://github.com/owncloud/core/issues/23599.

**Closed by danimo** 2016-04-03 15:58 UTC
