### ISSUE TITLE
Configuration Error on the Features Contact Form

### ISSUE THREAD

**Issue by lefherz** [owncloud/owncloud.org#1360] opened 2018-01-03 14:38 UTC
There is a contact form on https://owncloud.org/features/, where some of the code is displaying, instead of clean text.

```
[md-form]
[md-text label="Your name (required)"]
Amanda
[/md-text]
```

It works, but the looks could be improved.

**Comment by patrickjahns** [comment] 2018-01-04 10:07
Screenshot:
![image](https://user-images.githubusercontent.com/6403243/34558724-7c26d4e6-f13f-11e7-8963-8375255b8436.png)

**Comment by patrickjahns** [comment] 2018-01-04 10:08
Duplicate of #1355

**Closed by patrickjahns** 2018-01-04 10:08 UTC
