### ISSUE TITLE
Publish fingerprints when changing repository signing keys

### ISSUE THREAD

**Issue by 9662** [owncloud/owncloud.org#1106] opened 2016-11-26 02:30 UTC
The OpenSUSE repository (Leap 42.1 anyway) got a new GPG key some time ago. In order for updates (including automatic updates) to be applied, I am required to manually trust the key first, as it is not signed by anyone else in the system's chain of trust.

However, I cannot seem to find a reference to what the expected key should be anywhere on the web.

Not cool, chaps. One would not want to be on the receiving end of a [WordPress-class pwnage](https://www.wordfence.com/blog/2016/11/hacking-27-web-via-wordpress-auto-update/ "Ouch! That must have hurt"), would one?

So do us a favour and publish, somewhere where it can be half-trusted, such as https://owncloud.org/ or better, here in GitHub¹, the *correct* keys for the repos that you host, along with their fingerprints if possible.

I do note (after heavy Googling) that you have linked to [this public key](https://owncloud.org/owncloud.asc) from here: https://owncloud.org/install/#edition. Unfortunately that is not the same as [the key](http://download.owncloud.org/download/repositories/stable/openSUSE_Leap_42.1/repodata/repomd.xml.key) currently live on the [OpenSUSE Leap 42.1 repo](http://download.owncloud.org/download/repositories/stable/openSUSE_Leap_42.1), so at the moment I am unable to check for updates to my installation, as I cannot verify the authenticity of the key.

¹ https://github.com/owncloud/owncloud.org/blob/master/assets/files/obs-release-signing.gpg published by @LukasReschke is waiting for #1079 but that has not been merged yet, so I cannot trust it.

**Comment by RealRancor** [comment] 2016-11-26 10:51
Duplicate of https://github.com/owncloud/owncloud.org/issues/1076

**Comment by 9662** [comment] 2016-11-26 15:40
@RealRancor : Not a duplicate mate. Haven't you read the footnote?

> ¹ https://github.com/owncloud/owncloud.org/blob/master/assets/files/obs-release-signing.gpg published by @LukasReschke is waiting for #1079 **but that has not been merged yet, so I cannot trust it.**

In other words, how do I know that you are still a bona fide contributor? I can also create a pull request with whatever keys I want, and it would be audacious—to say the least—for anyone to trust it until it goes into master.

Yet it looks like someone has put that key on the production server already, even though it hasn't been merged yet. That's a bit shoddy, security-wise. A better solution may be to push the keys to master first, and then on deploying master replace the repo keys at the same time (or maybe you can do some symlink magic for extra cred, though I haven't thought this through, alliteratively speaking).

**Comment by 9662** [comment] 2016-11-26 15:49
Also, publishing the key fingerprint would probably make life easier to those who are happy just checking that, instead of importing the key manually. The former is a more straightforward workflow at least on OpenSUSE—on coming across an untrusted key, it presents its key ID and fingerprint and asks the user whether or not to trust and for how long.

**Comment by RealRancor** [comment] 2016-11-26 16:21
Mate, you got me. Tried to P0wn your oC Installation with that :see_no_evil:

**Comment by 9662** [comment] 2016-11-26 20:13
Beg pardon?

**Comment by RealRancor** [comment] 2016-11-26 20:33
> In other words, how do I know that you are still a bona fide contributor? I can also create a pull request with whatever keys I want, and it would be audacious—to say the least—for anyone to trust it until it goes into master.

**Comment by 9662** [comment] 2016-11-27 17:09
Switched from @owncloud to @nextcloud so as not to jeopardise my organisation's ISO 27001 present and future compliance status.

**Comment by RealRancor** [comment] 2016-11-27 17:27
@9662 Just to clarify: I'm just talking here for myself and from my experience. I'm not related to ownCloud and the community behind it.

Stuff like this just takes ages in the ownCloud world.

**Comment by Kawohl** [comment] 2016-11-27 19:05
@jnweiger @crrodriguez

**Closed** 2020-12-23 11:39 UTC
Labels: before relaunch
