### ISSUE TITLE
https://owncloud.org/install/#edition missing hash and signature download links.

### ISSUE THREAD

**Issue by tlhonmey** [owncloud/owncloud.org#1167] opened 2017-03-27 19:00 UTC
https://owncloud.org/install/#edition 

This page has "(.tar.bz2 / .zip) " structures which imply that there should be downloads available for hashes and signatures of the archive files.

These structures do not actually contain any links.

Either links to current hashes/signatures should be added back to the page, or the "(.tar.bz2 / .zip)" sections should be replaced with links to the archive page where download links are available.

**Comment by tony5** [comment] 2017-03-27 19:11
I agree with @tlhonmey 
I think step #2 of the installation instruction should be a link pointing to https://owncloud.org/changelog/
to make locating the sums easier.

**Comment by kdslkdsaldsal** [comment] 2017-03-31 06:01
This is a duplicate of https://github.com/owncloud/owncloud.org/issues/1074

**Comment by hurradieweltgehtunter** [comment] 2017-12-21 09:39
Download page has completely new structure after relaunch. I hope the new structure is correct. If not please let me know.

**Closed by hurradieweltgehtunter** 2017-12-21 09:39 UTC
Labels: before relaunch
