### ISSUE TITLE
Blog not easy to find from main page, potential broken link

### ISSUE THREAD

**Issue by PVince81** [owncloud/owncloud.org#1308] opened 2017-10-25 10:52 UTC
### Steps

1. Open https://owncloud.org
1. Scan the page visually for "blog" => not found
1. Click on "News" and wonder "is that the blog or is that news ?"
1. Feel confused
1. Type https://owncloud.org/blog => not found, 404
1. Give up

### Expected result
Blog easy to find on the main page, maybe have a "Blog" entry behind "News" in the header.
The URL "https://owncloud.org/blog" must link to the blog index. Currently it's a 404 page, maybe it's a bug because blog articles do start with that URL: https://owncloud.org/blog/good-bye-apps-owncloud-com/

### Actual result
Confusion

**Comment by PVince81** [comment] 2017-10-25 10:54
Furthermore, when on a blog post page like https://owncloud.org/blog/good-bye-apps-owncloud-com/, there should be a way to go back to the blog index / the main blog page that lists all article.

From this article I'm unable to navigate to any other article.

**Comment by PVince81** [comment] 2017-10-25 10:56
Ok, so it turns out that the "News" link is what points to the blog.

Would be good to have a more compact index there or something in the sidebar to be able to quickly jump to previous articles. I was looking for this article https://owncloud.org/blog/meet-fellow-ownclouders-online-with-video/ and had to scroll down below the first article. I knew that it was a recent article. I was expecting to see it as the 2nd or 3rd entry in some kind of compact list.

**Comment by kdslkdsaldsal** [comment] 2017-11-24 21:50
Looks like mostly a duplicate of https://github.com/owncloud/owncloud.org/issues/1060

**Comment by Kawohl** [comment] 2017-12-20 12:39
With the new page we have aggregated everything to /news. 
Please feel to reopen if you think we need a news section.

**Closed by Kawohl** 2017-12-20 12:39 UTC
